//! Lockfile format for T-Rex (rx.lock)
//!
//! The lockfile captures the exact resolved versions of all dependencies,
//! including transitive dependencies, with download URLs and hashes.

use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::resolver::{ResolvedPackage, Resolution};
use crate::{Error, Result};

/// Lockfile format version
pub const LOCKFILE_VERSION: &str = "1";

/// The lockfile (rx.lock)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lockfile {
    /// Lockfile format version
    pub version: String,

    /// Locked packages (sorted by name for deterministic output)
    #[serde(default)]
    pub packages: BTreeMap<String, LockedPackage>,
}

/// A locked package with its exact version and metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedPackage {
    /// Exact version
    pub version: String,

    /// Download URL
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,

    /// Hash for verification (format: "algorithm:hash")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,

    /// Direct dependencies of this package
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

impl Lockfile {
    /// Create a new empty lockfile
    pub fn new() -> Self {
        Self {
            version: LOCKFILE_VERSION.to_string(),
            packages: BTreeMap::new(),
        }
    }

    /// Create a lockfile from a resolution
    pub fn from_resolution(resolution: &Resolution) -> Self {
        let mut packages = BTreeMap::new();

        for pkg in &resolution.packages {
            packages.insert(
                pkg.name.clone(),
                LockedPackage {
                    version: pkg.version.clone(),
                    url: if pkg.url.is_empty() {
                        None
                    } else {
                        Some(pkg.url.clone())
                    },
                    hash: if pkg.hash.is_empty() {
                        None
                    } else {
                        Some(pkg.hash.clone())
                    },
                    dependencies: vec![], // TODO: Track dependency graph
                },
            );
        }

        Self {
            version: LOCKFILE_VERSION.to_string(),
            packages,
        }
    }

    /// Load a lockfile from disk
    pub fn load(path: &Path) -> Result<Self> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| Error::Io(e))?;
        Self::parse(&content)
    }

    /// Parse lockfile content
    pub fn parse(content: &str) -> Result<Self> {
        toml::from_str(content).map_err(Error::TomlParse)
    }

    /// Save lockfile to disk
    pub fn save(&self, path: &Path) -> Result<()> {
        let content = self.to_string()?;
        std::fs::write(path, content).map_err(Error::Io)
    }

    /// Convert to TOML string
    pub fn to_string(&self) -> Result<String> {
        // Add header comment
        let mut output = String::new();
        output.push_str("# This file is automatically generated by T-Rex.\n");
        output.push_str("# Do not edit manually.\n\n");

        let toml = toml::to_string_pretty(self).map_err(Error::TomlSerialize)?;
        output.push_str(&toml);

        Ok(output)
    }

    /// Convert back to a Resolution for installation
    pub fn to_resolution(&self) -> Resolution {
        let packages = self
            .packages
            .iter()
            .map(|(name, pkg)| ResolvedPackage {
                name: name.clone(),
                version: pkg.version.clone(),
                url: pkg.url.clone().unwrap_or_default(),
                hash: pkg.hash.clone().unwrap_or_default(),
            })
            .collect();

        Resolution { packages }
    }

    /// Get a locked package by name
    pub fn get(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.get(name)
    }

    /// Check if a package is locked
    pub fn contains(&self, name: &str) -> bool {
        self.packages.contains_key(name)
    }

    /// Number of locked packages
    pub fn len(&self) -> usize {
        self.packages.len()
    }

    /// Check if empty
    pub fn is_empty(&self) -> bool {
        self.packages.is_empty()
    }
}

impl Default for Lockfile {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_lockfile() {
        let lockfile = Lockfile::new();
        assert_eq!(lockfile.version, LOCKFILE_VERSION);
        assert!(lockfile.is_empty());
    }

    #[test]
    fn test_parse_lockfile() {
        let content = r#"
version = "1"

[packages.requests]
version = "2.28.0"
url = "https://example.com/requests-2.28.0.whl"
hash = "sha256:abc123"

[packages.urllib3]
version = "1.26.0"
"#;

        let lockfile = Lockfile::parse(content).unwrap();
        assert_eq!(lockfile.len(), 2);
        assert!(lockfile.contains("requests"));
        assert!(lockfile.contains("urllib3"));

        let requests = lockfile.get("requests").unwrap();
        assert_eq!(requests.version, "2.28.0");
        assert_eq!(requests.hash, Some("sha256:abc123".to_string()));
    }

    #[test]
    fn test_round_trip() {
        let mut lockfile = Lockfile::new();
        lockfile.packages.insert(
            "mypackage".to_string(),
            LockedPackage {
                version: "1.0.0".to_string(),
                url: Some("https://example.com/pkg.whl".to_string()),
                hash: Some("sha256:abc".to_string()),
                dependencies: vec![],
            },
        );

        let content = lockfile.to_string().unwrap();
        let parsed = Lockfile::parse(&content).unwrap();

        assert_eq!(parsed.len(), 1);
        let pkg = parsed.get("mypackage").unwrap();
        assert_eq!(pkg.version, "1.0.0");
    }
}
