use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::{Args, ValueEnum};

use rx_core::Lockfile;

#[derive(Debug, Clone, Copy, Default, ValueEnum)]
pub enum ExportFormat {
    /// Standard requirements.txt format (package==version)
    #[default]
    Requirements,
    /// Constraints format (same as requirements, used with -c flag)
    Constraints,
}

#[derive(Args)]
pub struct ExportCommand {
    /// Project directory (defaults to current directory)
    #[arg(long, default_value = ".")]
    pub project: PathBuf,

    /// Output format
    #[arg(long, short, value_enum, default_value = "requirements")]
    pub format: ExportFormat,

    /// Include hashes for verification (--hash=sha256:...)
    #[arg(long)]
    pub with_hashes: bool,

    /// Output file (defaults to stdout)
    #[arg(long, short)]
    pub output: Option<PathBuf>,

    /// Only include specific packages (optional, includes all by default)
    #[arg(long)]
    pub only: Vec<String>,

    /// Exclude specific packages
    #[arg(long)]
    pub exclude: Vec<String>,
}

impl ExportCommand {
    pub async fn run(self) -> Result<()> {
        let project_dir = if self.project.as_os_str() == "." {
            std::env::current_dir()?
        } else {
            self.project.canonicalize()?
        };

        let lockfile_path = project_dir.join("rx.lock");

        // Load lockfile
        let lockfile = Lockfile::load(&lockfile_path).with_context(|| {
            format!(
                "No rx.lock found in {:?}. Run 'rx lock' first.",
                project_dir
            )
        })?;

        if lockfile.is_empty() {
            println!("No packages in lockfile.");
            return Ok(());
        }

        // Generate output
        let output = self.generate_output(&lockfile)?;

        // Write output
        if let Some(output_path) = &self.output {
            std::fs::write(output_path, &output)
                .with_context(|| format!("Failed to write to {:?}", output_path))?;

            let format_name = match self.format {
                ExportFormat::Requirements => "requirements.txt",
                ExportFormat::Constraints => "constraints.txt",
            };
            println!(
                "✓ Exported {} packages to {:?} ({})",
                lockfile.len(),
                output_path,
                format_name
            );
        } else {
            // Write to stdout
            print!("{}", output);
        }

        Ok(())
    }

    fn generate_output(&self, lockfile: &Lockfile) -> Result<String> {
        let mut lines = Vec::new();

        // Add header comment
        lines.push(format!(
            "# Generated by T-Rex (rx export --format {})",
            match self.format {
                ExportFormat::Requirements => "requirements",
                ExportFormat::Constraints => "constraints",
            }
        ));
        lines.push(format!("# {} packages", lockfile.len()));
        lines.push(String::new());

        // Collect and filter packages
        let mut packages: Vec<_> = lockfile.packages.iter().collect();

        // Filter by --only if specified
        if !self.only.is_empty() {
            let only_lower: Vec<String> =
                self.only.iter().map(|s| s.to_lowercase()).collect();
            packages.retain(|(name, _)| only_lower.contains(&name.to_lowercase()));
        }

        // Filter by --exclude
        if !self.exclude.is_empty() {
            let exclude_lower: Vec<String> =
                self.exclude.iter().map(|s| s.to_lowercase()).collect();
            packages.retain(|(name, _)| !exclude_lower.contains(&name.to_lowercase()));
        }

        // Sort by name for deterministic output
        packages.sort_by(|a, b| a.0.cmp(b.0));

        // Generate lines
        for (name, pkg) in packages {
            let mut line = format!("{}=={}", name, pkg.version);

            if self.with_hashes {
                if let Some(hash) = &pkg.hash {
                    // Hash format in lockfile is "sha256:abc123"
                    // pip format is --hash=sha256:abc123
                    line.push_str(&format!(" \\\n    --hash={}", hash));
                }
            }

            lines.push(line);
        }

        // Add trailing newline
        lines.push(String::new());

        Ok(lines.join("\n"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rx_core::lockfile::LockedPackage;
    use std::collections::BTreeMap;

    fn create_test_lockfile() -> Lockfile {
        let mut packages = BTreeMap::new();
        packages.insert(
            "requests".to_string(),
            LockedPackage {
                version: "2.28.0".to_string(),
                url: Some("https://example.com/requests-2.28.0.whl".to_string()),
                hash: Some("sha256:abc123def456".to_string()),
                dependencies: vec![],
                markers: None,
                files: vec![],
            },
        );
        packages.insert(
            "urllib3".to_string(),
            LockedPackage {
                version: "1.26.0".to_string(),
                url: Some("https://example.com/urllib3-1.26.0.whl".to_string()),
                hash: Some("sha256:xyz789".to_string()),
                dependencies: vec![],
                markers: None,
                files: vec![],
            },
        );
        Lockfile {
            version: "1".to_string(),
            metadata: None,
            packages,
        }
    }

    #[test]
    fn test_basic_export() {
        let cmd = ExportCommand {
            project: PathBuf::from("."),
            format: ExportFormat::Requirements,
            with_hashes: false,
            output: None,
            only: vec![],
            exclude: vec![],
        };

        let lockfile = create_test_lockfile();
        let output = cmd.generate_output(&lockfile).unwrap();

        assert!(output.contains("requests==2.28.0"));
        assert!(output.contains("urllib3==1.26.0"));
        assert!(!output.contains("--hash"));
    }

    #[test]
    fn test_export_with_hashes() {
        let cmd = ExportCommand {
            project: PathBuf::from("."),
            format: ExportFormat::Requirements,
            with_hashes: true,
            output: None,
            only: vec![],
            exclude: vec![],
        };

        let lockfile = create_test_lockfile();
        let output = cmd.generate_output(&lockfile).unwrap();

        assert!(output.contains("requests==2.28.0"));
        assert!(output.contains("--hash=sha256:abc123def456"));
        assert!(output.contains("--hash=sha256:xyz789"));
    }

    #[test]
    fn test_export_only_filter() {
        let cmd = ExportCommand {
            project: PathBuf::from("."),
            format: ExportFormat::Requirements,
            with_hashes: false,
            output: None,
            only: vec!["requests".to_string()],
            exclude: vec![],
        };

        let lockfile = create_test_lockfile();
        let output = cmd.generate_output(&lockfile).unwrap();

        assert!(output.contains("requests==2.28.0"));
        assert!(!output.contains("urllib3"));
    }

    #[test]
    fn test_export_exclude_filter() {
        let cmd = ExportCommand {
            project: PathBuf::from("."),
            format: ExportFormat::Requirements,
            with_hashes: false,
            output: None,
            only: vec![],
            exclude: vec!["urllib3".to_string()],
        };

        let lockfile = create_test_lockfile();
        let output = cmd.generate_output(&lockfile).unwrap();

        assert!(output.contains("requests==2.28.0"));
        assert!(!output.contains("urllib3"));
    }
}
